<?xml version="1.0"?>
<!DOCTYPE clientes[<!--
raiz
-->
<!ELEMENT clientes (cliente+)>
<!ELEMENT	cliente (idcliente,empresa,contacto,ciudad)>
<!ELEMENT idcliente (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT contacto (telefono,correo)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

]>

<clientes>

<cliente>
<idcliente>1</idcliente>
<empresa>PUCESE</empresa>
<contacto>
	<telefono>9898</telefono>
	<correo>dsfsdwdsf</correo>
</contacto>
<ciudad>Esmeraldas</ciudad>
</cliente>

<cliente>
<idcliente>2</idcliente>
<empresa>PUCE</empresa>
<contacto>
	<telefono>2232323</telefono>
	<correo>dsfsdwdsf</correo>
</contacto>
<ciudad>Quito</ciudad>
</cliente>






</clientes>
