=== astrojebus/XML-XLS-DTD/empleadoXMLconSchema/empleadoSchema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="empleado">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nombre"/>
				<xsd:element ref="apellidos"/>
				<xsd:element ref="edad"/>
				<xsd:element ref="fechaNac"/>
				<xsd:element ref="direccion"/>
				<xsd:element ref="email"/>
				<xsd:element ref="curso"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="empleados">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="empleado" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="direccion" type="xsd:string"/>
	<xsd:element name="edad">
	
		<xsd:simpleType>
		<xsd:restriction base="xsd:integer">
		<xsd:minInclusive value="0"/>
		<xsd:maxInclusive value="100"/>
		</xsd:restriction>
		</xsd:simpleType>
		
	</xsd:element>
	
	<xsd:element name="curso">
	
		<xsd:simpleType>
		<xsd:restriction base="xsd:integer">
		<xsd:minInclusive value="1"/>
		<xsd:maxInclusive value="10"/>
		</xsd:restriction>
		</xsd:simpleType>
		
	</xsd:element>
	
	<xsd:element name="email" type="emailAddress"/>
	<xsd:simpleType name="emailAddress"> 
    <xsd:restriction base="xsd:string"> 
    <xsd:pattern value="[^@]+@[^\.]+\..+"/> 
    </xsd:restriction> 
 	</xsd:simpleType> 
	
	<xsd:element name="apellidos" type="xsd:string"/>
	<xsd:element name="nombre" type="xsd:string"/>
	<xsd:element name="fechaNac" type="xsd:date"/>
</xsd:schema>

=== astrojebus/XML-XLS-DTD/empleadoXMLconSchema/empleadoXML.xml
<?xml version="1.0"?>

<empleados
xmlns="http://your_namespace"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation="http://your_namespace
				C:\Users\Jesus\Desktop\empleadoXMLconSchema\empleadoSchema.xsd">
	<empleado>
		<nombre>Juan</nombre>
		<apellidos>Cortes</apellidos>
		<edad>24</edad>
		<fechaNac>1991-08-10</fechaNac>
		<direccion>Esmeraldas</direccion>
		<email>erer@hotmail.com</email>
		<curso>6</curso>
	</empleado>
	
	<empleado>
		<nombre>Manuel</nombre>
		<apellidos>Tello</apellidos>
		<edad>34</edad>
		<fechaNac>1988-04-16</fechaNac>
		<direccion>Quito</direccion>
		<email>email2@hotmail.com</email>
		<curso>3</curso>
	</empleado>
	<empleado>
		<nombre>Rosa</nombre>
		<apellidos>MMM</apellidos>
		<edad>25</edad>
		<fechaNac>1999-05-10</fechaNac>
		<direccion>Esmeraldas</direccion>
		<email>mmmm1@hotmail.com</email>
		<curso>5</curso>
	</empleado>
	<empleado>
		<nombre>Cesas</nombre>
		<apellidos>Larrea</apellidos>
		<edad>22</edad>
		<fechaNac>1986-05-10</fechaNac>
		<direccion>Esmeraldas</direccion>
		<email>gemail1@hotmail.com</email>
		<curso>8</curso>
	</empleado>
	<empleado>
		<nombre>Andrea</nombre>
		<apellidos>Velez</apellidos>
		<edad>34</edad>
		<fechaNac>1993-03-04</fechaNac>
		<direccion>Esmeraldas</direccion>
		<email>geee3@hotmail.com</email>
		<curso>8</curso>
	</empleado>
	<empleado>
		<nombre>Raul</nombre>
		<apellidos>Cartillo</apellidos>
		<edad>34</edad>
		<fechaNac>1987-05-17</fechaNac>
		<direccion>Esmeraldas</direccion>
		<email>mmmm@hotmail.com</email>
		<curso>4</curso>
	</empleado>
</empleados>
